name: Generate ICS File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir -p output

    - name: Run Python script to download and convert Excel to ICS
      run: python convert_to_ics.py

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git add academic_calendar.ics
        git commit -m "Update academic calendar ICS file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token for authentication
